version: '3'

services:
  silverstripe:
    build: docker/7.4
    image: devart/ss7.4
    networks:
      default:
        aliases:
          - silverstripe.test
    volumes:
       - .:/var/www/html    
       - ~/.composer:/root/.composer
    depends_on:
       - database
    ports:
       - 80:80
    environment:
       - DOCUMENT_ROOT=/var/www/html/public
  database:
    image: mysql:5.7
    environment:
       - MYSQL_ROOT_PASSWORD=root
    volumes:
       - mysql57:/var/lib/mysql
    ports:
       - 3306:3306
volumes:
  mysql57: